name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

  APP_DATABASE__USER: postgres
  APP_DATABASE__PASSWORD: password
  APP_DATABASE__HOST: localhost
  APP_DATABASE__NAME: postgres
  APP_HOST: 0.0.0.0
  APP_PORT: 8000

jobs:
  pipeline:
    name: Full Pipeline
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ env.APP_DATABASE__USER }}
          POSTGRES_PASSWORD: ${{ env.APP_DATABASE__PASSWORD }}
          POSTGRES_DB: ${{ env.APP_DATABASE__NAME }}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
